version: "3.9"

services:
  web-prestamos:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_NODE_ENV: production
        VITE_REACT_APP_API_URL: REPLACE_API_URL
        VITE_REACT_APP_USE_MOCK_API: "false"
        VITE_REACT_APP_ENABLE_DEBUG: "false"
        VITE_REACT_APP_ENABLE_ANALYTICS: "true"
    image: web-prestamos-app
    container_name: web-prestamos-app
    ports:
      - "3010:3000"
    restart: unless-stopped
    networks:
      - web-prestamos-network

networks:
  web-prestamos-network:
    driver: bridge
